server:
  port: 8060

data:
  mode:
    comparegenerate: true
    compareupdate: false
  upload:
    input:
      skipHeader: true
  process:
    sedathreads: 5
    csvthreads: 3

logging:
  level:
    com.yantriks: DEBUG

urban:
  sterling:
    protocol: http
    url: localhost:7001
    apitester:
      userid: admin
      password: password
  yantriks:
    availabilityproduct: yas
    inventoryproduct: ilt
    masterdataproduct: ycs
    protocol: http
    timeout: 1000
    availability:
        host: localhost
        port: 8080
    inventorylite:
        host: localhost:8096
        port: 8096
    masterdata:
        host: localhost
        port: 8094

yantriks:
  default:
    orgid: URBN
    fulfillmentservice: STANDARD
    segment: DEFAULT