server:
  port: 8060

data:
  input:
    absolutedirectory: D:\temp
    filename: sample.csv
    option:
      noop: true
      maxMessagesPerPoll: 1
      delay: 1000
  output:
    absolutedirectory: D:\temp
    filename: outsample.csv
    option:
      fileexists: Append
  mode:
    comparegenerate: false
    compareupdate: true
  upload:
    input:
      skipHeader: true
  process:
    sedathreads: 5
    csvthreads: 3

logging:
  level:
    com.yantriks: DEBUG

urban:
  sterling:
    protocol: http
    url: 10.75.27.87:8080
    apitester:
      userid: admin
      password: password
  yantriks:
    availabilityproduct: yas
    inventoryproduct: ilt
    masterdataproduct: ycs
    protocol: https
    timeout: 10000
    availability:
        host: https://34.102.178.188
        port:
    inventorylite:
        host: localhost:8096
        port: 8096
    masterdata:
        host: localhost
        port: 8094

yantriks:
  default:
    orgid: URBN
    fulfillmentservice: STANDARD
    segment: DEFAULT

graceful:
  shutdown:
    timeoutinseconds: 300

seda:
  queue: urbandatacompare
