server:
  port: 8060

spring:
  main:
    allow-bean-definition-overriding: true

ribbon:
  eureka:
    enabled: false
  EnableZoneAffinity: true
  IsSecure: true

data:
  input:
    absolutedirectory: D:\temp\input\
    filename: sample_0Error.csv
    option:
      noop: true
      maxMessagesPerPoll: 1
      delay: 1000
  output:
    absolutedirectory: D:\temp\output\
    filename: output.csv
    option:
      fileexists: Append
  mode:
    comparegenerate: false
    compareupdate: true
  upload:
    input:
      skipHeader: true
  process:
    sedathreads: 1
    csvthreads: 1

logging:
  level:
    com.yantriks: DEBUG

urban:
  sterling:
    protocol: http
    url: sushqssteriap01.urbanout.com:8080 #STAGING -sushqssteriap01.urbanout.com:8080 #PROD - sushqpsterapp01.urbanout.com:8080 #STAGING - 10.75.31.180:8080 #DEV - 10.75.27.87:8080
    apitester:
      userid: admin
      password: password
  yantriks:
    availabilityproduct: yas
    inventoryproduct: ilt
    masterdataproduct: ycs
    protocol: https
    timeout: 10000
    availability:
#      host: staging-yantriks-api.urbncloud.com/availability #PROD - yantriks-api.urbncloud.com/availability #yantriks-dev-availability-api01.urbn.com   #yantriks-api.urbncloud.com/availability       #STAGING - staging-yantriks-api.urbncloud.com/availability # #34.102.178.188
      host: "35.186.197.207"
      host2: staging-yantriks-api.urbncloud.com/availability #"https://35.186.197.207"
      port:
    inventorylite:
      host: localhost
      port: 8096
    masterdata:
      host: localhost
      port: 8094

yantriks:
  default:
    orgid: URBN
    fulfillmentservice: STANDARD
    segment: DEFAULT

graceful:
  shutdown:
    timeoutinseconds: 300

seda:
  queue: urbandatacompare
  queueSize: 10000

apicall:
  newHttpClientCall: false


security:
  secretKey: c3VwZXJzZWNyZXRzdHJpbmdmb3JzdGFnaW5nc3Rlcmxpbmc #PROD - ZjNlYzliMDExMGUwMWMyYTM1ODc1NzM2ZGUyNGUzM2RhMDQ2YzNiMTY5OTAxY2ZlNWJlZDFkMGExOGRlZWQ5OA #SSTAGING - c3VwZXJzZWNyZXRzdHJpbmdmb3JzdGFnaW5nc3Rlcmxpbmc
  skid: STERLING-1
  expireTime: 3600


feign:
  httpclient:
    maxConnections: 10
    maxConnectionsPerRoute: 5
  retry:
    period: 40000
    duration: 360000
    maxAttempts: 3